import { CollaborationProps } from "../types/collaboration";

export const collaborations: CollaborationProps[] = [
  {
    company: "DLTCode S.L.",
    role: {
      en: "Frontend Developer",
      es: "Desarrollador Frontend",
      it: "Sviluppatore Frontend",
      de: "Frontend-Entwickler",
      fr: "Développeur Frontend",
    },
    period: {
      en: "Apr 2025 - Apr 2026",
      es: "Abr 2025 - Abr 2026",
      it: "Apr 2025 - Apr 2026",
      de: "Apr 2025 - Apr 2026",
      fr: "Avr 2025 - Avr 2026",
    },
    description: {
      en: "Development of web applications in collaborative environments with backend integration, working on 5 projects: ITB, S@IC, ATS, Osborne and DStar. Implementation of scalable interfaces using Next.js and SCSS, applying performance optimization, accessibility, component reusability, and fidelity to UI/UX designs.",
      es: "Desarrollo de aplicaciones web en entornos colaborativos con integración backend, trabajando en 5 proyectos: ITB, S@IC, ATS, Osborne y DStar. Implementación de interfaces escalables usando Next.js y SCSS, aplicando optimización de rendimiento, accesibilidad, reutilización de componentes y fidelidad a diseños UI/UX.",
      it: "Sviluppo di applicazioni web in ambienti collaborativi con integrazione backend, lavorando su 5 progetti: ITB, S@IC, ATS, Osborne e DStar. Implementazione di interfacce scalabili utilizzando Next.js e SCSS, applicando ottimizzazione delle prestazioni, accessibilità, riutilizzabilità dei componenti e fedeltà ai design UI/UX.",
      de: "Entwicklung von Webanwendungen in kollaborativen Umgebungen mit Backend-Integration, Arbeit an 5 Projekten: ITB, S@IC, ATS, Osborne und DStar. Implementierung skalierbarer Interfaces mit Next.js und SCSS, Anwendung von Leistungsoptimierung, Barrierefreiheit, Komponentenwiederverwendbarkeit und UI/UX-Design-Treue.",
      fr: "Développement d'applications web dans des environnements collaboratifs avec intégration backend, travail sur 5 projets : ITB, S@IC, ATS, Osborne et DStar. Implémentation d'interfaces évolutives utilisant Next.js et SCSS, appliquant l'optimisation des performances, l'accessibilité, la réutilisabilité des composants et la fidélité aux designs UI/UX.",
    },
    achievements: {
      en: [
        "Worked on 5 projects: ITB, S@IC, ATS, Osborne and DStar",
        "Implementation of scalable interfaces using Next.js and SCSS",
        "Performance optimization and accessibility improvements",
        "Creation of technical frontend documentation to improve maintainability",
      ],
      es: [
        "Trabajo en 5 proyectos: ITB, S@IC, ATS, Osborne y DStar",
        "Implementación de interfaces escalables usando Next.js y SCSS",
        "Optimización de rendimiento y mejoras de accesibilidad",
        "Creación de documentación técnica frontend para mejorar el mantenimiento",
      ],
      it: [
        "Lavoro su 5 progetti: ITB, S@IC, ATS, Osborne e DStar",
        "Implementazione di interfacce scalabili utilizzando Next.js e SCSS",
        "Ottimizzazione delle prestazioni e miglioramenti dell'accessibilità",
        "Creazione di documentazione tecnica frontend per migliorare la manutenibilità",
      ],
      de: [
        "Arbeit an 5 Projekten: ITB, S@IC, ATS, Osborne und DStar",
        "Implementierung skalierbarer Interfaces mit Next.js und SCSS",
        "Leistungsoptimierung und Barrierefreiheitsverbesserungen",
        "Erstellung technischer Frontend-Dokumentation zur Verbesserung der Wartbarkeit",
      ],
      fr: [
        "Travail sur 5 projets : ITB, S@IC, ATS, Osborne et DStar",
        "Implémentation d'interfaces évolutives utilisant Next.js et SCSS",
        "Optimisation des performances et améliorations de l'accessibilité",
        "Création de documentation technique frontend pour améliorer la maintenabilité",
      ],
    },
    teamSize: {
      en: "Collaborative team",
      es: "Equipo colaborativo",
      it: "Team collaborativo",
      de: "Kollaboratives Team",
      fr: "Équipe collaborative",
    },
    image: "/exp/DltCode.webp",
  },
  {
    company: "FSC TopNutrition",
    role: {
      en: "Ecommerce Developer (Freelance)",
      es: "Desarrollador Ecommerce (Freelance)",
      it: "Sviluppatore Ecommerce (Freelance)",
      de: "Ecommerce-Entwickler (Freelance)",
      fr: "Développeur Ecommerce (Freelance)",
    },
    period: {
      en: "Jan 2023 - Present",
      es: "Ene 2023 - Actualmente",
      it: "Gen 2023 - Presente",
      de: "Jan 2023 - Gegenwärtig",
      fr: "Jan 2023 - Présent",
    },
    description: {
      en: "Personal project involving the development of a full-stack e-commerce web application using Next.js and Tailwind CSS, deployed on Vercel. Uses Supabase as the backend for authentication, database management, and storage, with secure payments through Stripe.",
      es: "Proyecto personal que implica el desarrollo de una aplicación web ecommerce full-stack usando Next.js y Tailwind CSS, desplegada en Vercel. Usa Supabase como backend para autenticación, gestión de base de datos y almacenamiento, con pagos seguros mediante Stripe.",
      it: "Progetto personale che coinvolge lo sviluppo di un'applicazione web e-commerce full-stack utilizzando Next.js e Tailwind CSS, distribuita su Vercel. Utilizza Supabase come backend per autenticazione, gestione del database e archiviazione, con pagamenti sicuri tramite Stripe.",
      de: "Persönliches Projekt involving die Entwicklung einer Full-Stack-E-Commerce-Webanwendung mit Next.js und Tailwind CSS, bereitgestellt auf Vercel. Verwendet Supabase als Backend für Authentifizierung, Datenbankverwaltung und Speicherung, mit sicheren Zahlungen über Stripe.",
      fr: "Projet personnel impliquant le développement d'une application web e-commerce full-stack utilisant Next.js et Tailwind CSS, déployée sur Vercel. Utilise Supabase comme backend pour l'authentification, la gestion de base de données et le stockage, avec des paiements sécurisés via Stripe.",
    },
    achievements: {
      en: [
        "Full-stack e-commerce development with Next.js and Tailwind CSS",
        "Integration of Supabase for authentication, database, and storage",
        "Secure payment integration through Stripe",
        "Transaction email sending via Resend and admin panel for products, orders, and users",
      ],
      es: [
        "Desarrollo ecommerce full-stack con Next.js y Tailwind CSS",
        "Integración de Supabase para autenticación, base de datos y almacenamiento",
        "Integración de pagos seguros mediante Stripe",
        "Envío de emails transaccionales vía Resend y panel de admin para productos, pedidos y usuarios",
      ],
      it: [
        "Sviluppo e-commerce full-stack con Next.js e Tailwind CSS",
        "Integrazione di Supabase per autenticazione, database e archiviazione",
        "Integrazione di pagamenti sicuri tramite Stripe",
        "Invio di email transazionali tramite Resend e pannello di amministrazione per prodotti, ordini e utenti",
      ],
      de: [
        "Full-Stack-E-Commerce-Entwicklung mit Next.js und Tailwind CSS",
        "Integration von Supabase für Authentifizierung, Datenbank und Speicherung",
        "Sichere Zahlungsintegration über Stripe",
        "Transaktions-E-Mail-Versand über Resend und Admin-Panel für Produkte, Bestellungen und Benutzer",
      ],
      fr: [
        "Développement e-commerce full-stack avec Next.js et Tailwind CSS",
        "Intégration de Supabase pour l'authentification, la base de données et le stockage",
        "Intégration de paiements sécurisés via Stripe",
        "Envoi d'e-mails transactionnels via Resend et panneau d'administration pour produits, commandes et utilisateurs",
      ],
    },
    teamSize: {
      en: "Solo developer",
      es: "Desarrollador individual",
      it: "Sviluppatore singolo",
      de: "Einzelentwickler",
      fr: "Développeur solo",
    },
    image: "/exp/FSC.webp",
  },
  {
    company: "NewLine Events (RealMadrid CF)",
    role: {
      en: "VIP Area Hostess",
      es: "Azafata de Zona VIP",
      it: "Hostess Area VIP",
      de: "VIP-Bereich Hostess",
      fr: "Hôtesse de Zone VIP",
    },
    period: {
      en: "Jan 2023 - Jun 2025",
      es: "Ene 2023 - Jun 2025",
      it: "Gen 2023 - Giu 2025",
      de: "Jan 2023 - Jun 2025",
      fr: "Jan 2023 - Jun 2025",
    },
    description: {
      en: "Welcome VIP customers and ensure they have a pleasant experience from the moment they arrive. Provide personalised customer service assistance during the event, offering information about the stadium and dealing with special requests.",
      es: "Dar la bienvenida a clientes VIP y asegurar que tengan una experiencia agradable desde el momento en que llegan. Proporcionar asistencia personalizada de atención al cliente durante el evento, ofreciendo información sobre el estadio y atendiendo solicitudes especiales.",
      it: "Accogliere i clienti VIP e garantire che abbiano un'esperienza piacevole dal momento del loro arrivo. Fornire assistenza personalizzata per il servizio clienti durante l'evento, offrendo informazioni sullo stadio e gestendo richieste speciali.",
      de: "VIP-Kunden willkommen heißen und sicherstellen, dass sie vom Moment ihrer Ankunft an eine angenehme Erfahrung haben. Personalisierte Kundenservice-Assistenz während der Veranstaltung, mit Informationen über das Stadion und besonderen Anfragen.",
      fr: "Accueillir les clients VIP et garantir qu'ils ont une expérience agréable dès leur arrivée. Fournir une assistance personnalisée au service client pendant l'événement, offrant des informations sur le stade et traitant les demandes spéciales.",
    },
    achievements: {
      en: [
        "Professional customer service at Santiago Bernabéu stadium",
        "Personalized attention for VIP guests during events",
        "Team coordination to deliver premium customer experience",
      ],
      es: [
        "Atención profesional al cliente en el estadio Santiago Bernabéu",
        "Atención personalizada para invitados VIP durante eventos",
        "Coordinación de equipo para ofrecer experiencia premium al cliente",
      ],
      it: [
        "Servizio clienti professionale allo stadio Santiago Bernabéu",
        "Attenzione personalizzata per gli ospiti VIP durante gli eventi",
        "Coordinamento del team per offrire un'esperienza cliente premium",
      ],
      de: [
        "Professioneller Kundenservice im Santiago Bernabéu Stadion",
        "Personalisierte Betreuung für VIP-Gäste bei Veranstaltungen",
        "Teamkoordination zur Bereitstellung eines Premium-Kundenerlebnisses",
      ],
      fr: [
        "Service client professionnel au stade Santiago Bernabéu",
        "Attention personnalisée pour les invités VIP pendant les événements",
        "Coordination d'équipe pour offrir une expérience client premium",
      ],
    },
    teamSize: {
      en: "Events team",
      es: "Equipo de eventos",
      it: "Team eventi",
      de: "Events-Team",
      fr: "Équipe d'événements",
    },
    image: "/exp/NewLine.webp",
  },
  {
    company: "Coop. soc. IL SOGNO arl",
    role: {
      en: "Web and Network Maintenance Technician",
      es: "Técnico de Mantenimiento Web y Redes",
      it: "Tecnico di Manutenzione Web e Reti",
      de: "Web- und Netzwerkwartungstechniker",
      fr: "Technicien de Maintenance Web et Réseaux",
    },
    period: {
      en: "Mar 2022 - Jun 2022",
      es: "Mar 2022 - Jun 2022",
      it: "Mar 2022 - Giu 2022",
      de: "Mär 2022 - Jun 2022",
      fr: "Mar 2022 - Jun 2022",
    },
    description: {
      en: "Part of a dedicated and dynamic group keeping the network and office equipment in top shape. Maintained one of the company websites, ensuring everything ran smoothly and customers had the best possible experience. Erasmus+ WBL placement in Rome, Italy.",
      es: "Parte de un grupo dedicado y dinámico que mantiene la red y el equipo de oficina en óptimas condiciones. Mantuvo uno de los sitios web de la empresa, asegurando que todo funcionara correctamente y los clientes tuvieran la mejor experiencia posible. Prácticas Erasmus+ WBL en Roma, Italia.",
      it: "Parte di un gruppo dedicato e dinamico che mantiene la rete e le attrezzature per ufficio in ottime condizioni. Ha mantenuto uno dei siti web dell'azienda, garantendo che tutto funzionasse correttamente e che i clienti avessero la migliore esperienza possibile. Tirocinio Erasmus+ WBL a Roma, Italia.",
      de: "Teil einer engagierten und dynamischen Gruppe, die das Netzwerk und die Büroausrüstung in bestem Zustand hält. Wartete eine der Firmenwebsites, stellte sicher, dass alles reibungslos lief und Kunden die bestmögliche Erfahrung hatten. Erasmus+ WBL-Praktikum in Rom, Italien.",
      fr: "Partie d'un groupe dédié et dynamique maintenant le réseau et l'équipement de bureau en parfait état. A maintenu l'un des sites web de l'entreprise, garantissant que tout fonctionnait correctement et que les clients avaient la meilleure expérience possible. Stage Erasmus+ WBL à Rome, Italie.",
    },
    achievements: {
      en: [
        "Network and office equipment maintenance",
        "Company website maintenance and optimization",
        "Erasmus+ international work experience in Rome, Italy",
      ],
      es: [
        "Mantenimiento de redes y equipos de oficina",
        "Mantenimiento y optimización del sitio web de la empresa",
        "Experiencia laboral internacional Erasmus+ en Roma, Italia",
      ],
      it: [
        "Manutenzione della rete e delle attrezzature per ufficio",
        "Manutenzione e ottimizzazione del sito web aziendale",
        "Esperienza lavorativa internazionale Erasmus+ a Roma, Italia",
      ],
      de: [
        "Netzwerk- und Büroausrüstungswartung",
        "Wartung und Optimierung der Firmenwebsite",
        "Erasmus+ internationale Berufserfahrung in Rom, Italien",
      ],
      fr: [
        "Maintenance du réseau et de l'équipement de bureau",
        "Maintenance et optimisation du site web de l'entreprise",
        "Expérience professionnelle internationale Erasmus+ à Rome, Italie",
      ],
    },
    teamSize: {
      en: "Small team (Rome)",
      es: "Equipo pequeño (Roma)",
      it: "Piccolo team (Roma)",
      de: "Kleines Team (Rom)",
      fr: "Petite équipe (Rome)",
    },
    image: "/exp/GentiEPaesi.webp",
  },
];
