import { CollaborationProps } from "../types/collaboration";

export const collaborations: CollaborationProps[] = [
  {
    company: "FSC Nutrition",
    role: {
      en: "Full-Stack & E-Commerce Developer",
      es: "Desarrollador Full-Stack & E-Commerce",
      it: "Sviluppatore Full-Stack & E-Commerce",
      de: "Full-Stack- & E-Commerce-Entwickler",
      fr: "Développeur Full-Stack & E-Commerce",
    },
    period: {
      en: "Apr 2026 - Present",
      es: "Abr 2026 - Presente",
      it: "Apr 2026 - Presente",
      de: "Apr 2026 - Heute",
      fr: "Avr 2026 - Présent",
    },
    description: {
      en: "End-to-end development of a high-performance e-commerce platform using Next.js and Tailwind CSS. Implementation of dynamic catalog, semantic AI search powered by Google Gemini, PostgreSQL relational database persistence, secure Stripe payment gateway with cryptographic webhooks, and executive admin dashboard with real-time sales metrics.",
      es: "Desarrollo integral de plataforma e-commerce de alto rendimiento con Next.js y Tailwind CSS. Implementación de catálogo dinámico, búsqueda semántica inteligente con IA (Gemini), persistencia en base de datos PostgreSQL, pasarela de pagos segura con Stripe y panel administrativo con analítica de ventas y gestión de pedidos.",
      it: "Sviluppo end-to-end di una piattaforma e-commerce ad alte prestazioni con Next.js e Tailwind CSS. Implementazione di catalogo dinamico, ricerca semantica con IA (Gemini), database PostgreSQL, gateway di pagamento Stripe e dashboard amministrativa con analisi delle vendite.",
      de: "End-to-End-Entwicklung einer leistungsstarken E-Commerce-Plattform mit Next.js und Tailwind CSS. Implementierung eines dynamischen Katalogs, semantischer KI-Suche mit Gemini, PostgreSQL-Datenbank, sicherer Stripe-Zahlungsabwicklung und Admin-Dashboard mit Verkaufsanalysen.",
      fr: "Développement complet d'une plateforme e-commerce haute performance avec Next.js et Tailwind CSS. Implémentation d'un catalogue dynamique, recherche sémantique avec IA (Gemini), base de données PostgreSQL, passerelle de paiement Stripe et tableau de bord d'administration avec analyses des ventes.",
    },
    achievements: {
      en: [
        "High-performance full-stack e-commerce engineering with Next.js, TypeScript and Tailwind CSS",
        "Implementation of intelligent semantic search engine with Gemini AI in natural language",
        "Relational database architecture on PostgreSQL for product catalog, inventory, and order fulfillment",
        "Secure Stripe payment integration with 3D Secure verification and real-time executive dashboard",
        "Automated transactional emails and order notifications with Resend",
      ],
      es: [
        "Desarrollo de plataforma e-commerce de alto rendimiento con Next.js, TypeScript y Tailwind CSS",
        "Integración de motor de búsqueda inteligente con IA (Gemini) en lenguaje natural",
        "Arquitectura de datos relacional en PostgreSQL para catálogo, stock y pedidos",
        "Pasarela de pagos segura con Stripe, webhooks verificados y panel de control administrativo",
        "Automatización de correos transaccionales y notificaciones de pedidos con Resend",
      ],
      it: [
        "Sviluppo e-commerce full-stack ad alte prestazioni con Next.js, TypeScript e Tailwind CSS",
        "Integrazione del motore di ricerca intelligente con Gemini AI in linguaggio naturale",
        "Architettura di database relazionale su PostgreSQL per catalogo, inventario e ordini",
        "Integrazione sicura dei pagamenti Stripe con webhooks verificati e dashboard esecutiva",
        "Email transazionali automatizzate e notifiche ordini con Resend",
      ],
      de: [
        "Full-Stack-E-Commerce-Entwicklung mit Next.js, TypeScript und Tailwind CSS",
        "Integration intelligenter semantischer Suche mit Gemini KI in natürlicher Sprache",
        "Relationale Datenbankarchitektur auf PostgreSQL für Produktkatalog, Bestand und Bestellungen",
        "Sichere Stripe-Zahlungsintegration mit verifizierten Webhooks und Management-Dashboard",
        "Automatisierter Transaktions-E-Mail-Versand und Bestellbenachrichtigungen über Resend",
      ],
      fr: [
        "Développement e-commerce full-stack haute performance avec Next.js, TypeScript et Tailwind CSS",
        "Intégration d'un moteur de recherche sémantique intelligent avec Gemini IA en langage naturel",
        "Architecture de base de données relationnelle sur PostgreSQL pour catalogue, stock et commandes",
        "Intégration sécurisée des paiements Stripe avec webhooks vérifiés et tableau de bord exécutif",
        "Envoi automatisé d'e-mails transactionnels et notifications de commandes via Resend",
      ],
    },
    techStack: ["Next.js", "React", "TypeScript", "TailwindCSS", "PostgreSQL", "Gemini AI", "Stripe API", "Resend"],
    impactMetrics: {
      en: [
        "94% semantic search accuracy with natural language AI recommendations",
        "Complete secure Stripe checkout flow and real-time inventory management dashboard",
        "Automated transactional emails and order confirmations with 99.9% deliverability",
      ],
      es: [
        "94% de precisión en recomendaciones semánticas con IA en lenguaje natural",
        "Flujo de pago integral seguro con Stripe y panel de control de inventario en tiempo real",
        "Emails transaccionales y confirmaciones de pedido automatizadas con 99.9% de entregabilidad",
      ],
      it: [
        "Precisione del 94% nella ricerca semantica con raccomandazioni IA in linguaggio naturale",
        "Flusso di pagamento sicuro con Stripe e dashboard di gestione inventario in tempo reale",
        "Email transazionali e conferme d'ordine automatizzate con consegnabilità del 99,9%",
      ],
      de: [
        "94% semantische Suchgenauigkeit mit KI-Empfehlungen in natürlicher Sprache",
        "Vollständiger sicherer Stripe-Checkout und Echtzeit-Inventar-Dashboard",
        "Automatisierte Transaktions-E-Mails und Bestellbestätigungen mit 99,9 % Zustellbarkeit",
      ],
      fr: [
        "Précision de recherche sémantique de 94% avec recommandations IA en langage naturel",
        "Flux de paiement sécurisé avec Stripe et tableau de bord de gestion d'inventaire en temps réel",
        "Emails transactionnels et confirmations de commande automatisés avec 99.9% de délivrabilité",
      ],
    },
    teamSize: {
      en: "Full-Stack Developer",
      es: "Desarrollador Full-Stack",
      it: "Sviluppatore Full-Stack",
      de: "Full-Stack-Entwickler",
      fr: "Développeur Full-Stack",
    },
    image: "/exp/FSC.webp",
    website: "https://fsctopnutrition.es",
  },
  {
    company: "DLTCode S.L.",
    role: {
      en: "Frontend Developer & AI Solutions",
      es: "Desarrollador Frontend & Integración IA",
      it: "Sviluppatore Frontend & Soluzioni IA",
      de: "Frontend-Entwickler & KI-Lösungen",
      fr: "Développeur Frontend & Solutions IA",
    },
    period: {
      en: "Apr 2025 - Apr 2026",
      es: "Abr 2025 - Abr 2026",
      it: "Apr 2025 - Apr 2026",
      de: "Apr 2025 - Apr 2026",
      fr: "Avr 2025 - Avr 2026",
    },
    description: {
      en: "Development of enterprise web applications and high-concurrency modules in collaborative environments, integrating backend services and AI solutions (conversational virtual assistants and customer support chatbots). Implementation of modern architectures and scalable design systems with Next.js, TypeScript, and SCSS, ensuring pixel-perfect fidelity to UI/UX designs and WCAG accessibility.",
      es: "Desarrollo de aplicaciones web corporativas y módulos de alta concurrencia en entornos colaborativos, con integración directa de servicios backend y soluciones de Inteligencia Artificial (asistentes virtuales conversacionales y chatbots de atención). Implementación de arquitecturas modernas y sistemas de diseño escalables con Next.js, TypeScript y SCSS, garantizando máxima fidelidad a maquetas UI/UX y accesibilidad WCAG.",
      it: "Sviluppo di applicazioni web aziendali e moduli ad alta concorrenza in ambienti collaborativi, integrando servizi backend e soluzioni IA (assistenti virtuali conversazionali e chatbot). Implementazione di architetture moderne con Next.js, TypeScript e SCSS, garantendo fedeltà UI/UX e accessibilità WCAG.",
      de: "Entwicklung von Unternehmens-Webanwendungen und hochkonsequenten Modulen in kollaborativen Umgebungen mit Integration von Backend-Diensten und KI-Lösungen (konversationelle virtuelle Assistenten und Support-Chatbots). Implementierung moderner Architekturen mit Next.js, TypeScript und SCSS mit höchster UI/UX-Treue und WCAG-Barrierefreiheit.",
      fr: "Développement d'applications web d'entreprise et de modules à haute concurrence dans des environnements collaboratifs, intégrant des services backend et des solutions IA (assistants virtuels conversationnels et chatbots de support). Implémentation d'architectures modernes avec Next.js, TypeScript et SCSS, garantissant une fidélité UI/UX maximale et l'accessibilité WCAG.",
    },
    achievements: {
      en: [
        "Development and integration of enterprise web interfaces and interactive modules using Next.js and SCSS",
        "Design and implementation of conversational AI assistants (Chatbots) for user query automation",
        "Robust integration with REST APIs and real-time backend microservices",
        "Standardization of a modular SCSS design system and reusable UI components across teams",
        "Core Web Vitals performance optimization and strict adherence to WCAG 2.1 AA accessibility standards",
      ],
      es: [
        "Desarrollo e integración de interfaces web corporativas y módulos interactivos con Next.js y SCSS",
        "Diseño e implementación de asistentes conversacionales (Chatbots con IA) para automatización de consultas",
        "Integración robusta con APIs REST y servicios de microservicios backend en tiempo real",
        "Estandarización del sistema modular de estilos SCSS y componentes de UI reutilizables",
        "Optimización de rendimiento (Core Web Vitals) y cumplimiento riguroso de accesibilidad WCAG 2.1 AA",
      ],
      it: [
        "Sviluppo e integrazione di interfacce web aziendali e moduli interattivi con Next.js e SCSS",
        "Progettazione e implementazione di assistenti conversazionali IA (Chatbot) per l'automazione",
        "Integrazione con API REST e microservizi backend in tempo reale",
        "Standardizzazione del sistema modulare SCSS e componenti riutilizzabili per i team",
        "Ottimizzazione delle prestazioni (Core Web Vitals) e conformità WCAG 2.1 AA",
      ],
      de: [
        "Entwicklung und Integration von Unternehmens-Webinterfaces und interaktiven Modulen mit Next.js und SCSS",
        "Design und Implementierung konversationeller KI-Assistenten (Chatbots) zur Prozessautomatisierung",
        "Robuste Integration mit REST-APIs und Echtzeit-Backend-Mikrodiensten",
        "Standardisierung eines modularen SCSS-Designsystems und wiederverwendbarer UI-Komponenten",
        "Core Web Vitals Leistungsoptimierung und strikte Einhaltung von WCAG 2.1 AA Barrierefreiheit",
      ],
      fr: [
        "Développement et intégration d'interfaces web d'entreprise et modules interactifs avec Next.js et SCSS",
        "Conception et implémentation d'assistants conversationnels IA (Chatbots) pour l'automatisation",
        "Intégration robuste avec APIs REST et microservices backend en temps réel",
        "Standardisation du système modulaire de styles SCSS et composants UI réutilisables",
        "Optimisation des performances (Core Web Vitals) et respect strict des normes WCAG 2.1 AA",
      ],
    },
    techStack: ["Next.js", "React", "TypeScript", "SCSS", "AI Chatbots", "REST APIs", "Git", "Figma", "WCAG 2.1 AA"],
    impactMetrics: {
      en: [
        "Successful delivery of enterprise platforms and AI conversational flows under strict deadlines",
        "Significant reduction in development cycle times via standardized reusable SCSS component system",
        "100% pixel-perfect fidelity to Figma mockups and 95+ score on accessibility benchmarks",
      ],
      es: [
        "Entrega exitosa de plataformas corporativas y flujos conversacionales con IA en plazos exigentes",
        "Reducción de tiempos de desarrollo mediante sistema de componentes SCSS reutilizables",
        "100% de fidelidad con diseños de Figma y puntuaciones superiores a 95 en accesibilidad",
      ],
      it: [
        "Rilascio riuscito di piattaforme aziendali e flussi conversazionali IA entro scadenze rigorose",
        "Riduzione dei tempi di sviluppo grazie al sistema di componenti SCSS standardizzato",
        "Fedeltà al 100% ai mockup Figma e punteggi superiori a 95 nei test di accessibilità",
      ],
      de: [
        "Erfolgreiche Bereitstellung von Unternehmensplattformen und KI-Chatbots in engen Fristen",
        "Verkürzung der Entwicklungszyklen durch wiederverwendbare SCSS-Komponenten",
        "100 % Treue zu Figma-Mockups und 95+ Bewertung bei Barrierefreiheits-Benchmarks",
      ],
      fr: [
        "Livraison réussie de plateformes d'entreprise et de flux conversationnels IA dans des délais stricts",
        "Réduction des temps de développement grâce au système de composants SCSS réutilisables",
        "100 % de fidélité aux maquettes Figma et score de plus de 95 aux critères d'accessibilité",
      ],
    },
    teamSize: {
      en: "Cross-functional team",
      es: "Equipo multidisciplinar",
      it: "Team multidisciplinare",
      de: "Multidisziplinäres Team",
      fr: "Équipe pluridisciplinaire",
    },
    image: "/exp/DltCode.webp",
    website: "https://dltcode.es/",
  },
  {
    company: "NewLine Events (RealMadrid CF)",
    role: {
      en: "VIP Area Hostess",
      es: "Azafata de Zona VIP",
      it: "Hostess Area VIP",
      de: "VIP-Bereich Hostess",
      fr: "Hôtesse de Zone VIP",
    },
    period: {
      en: "Jan 2023 - Jun 2025",
      es: "Ene 2023 - Jun 2025",
      it: "Gen 2023 - Giu 2025",
      de: "Jan 2023 - Jun 2025",
      fr: "Jan 2023 - Jun 2025",
    },
    description: {
      en: "Welcome VIP customers and ensure they have a pleasant experience from the moment they arrive. Provide personalised customer service assistance during the event, offering information about the stadium and dealing with special requests.",
      es: "Dar la bienvenida a clientes VIP y asegurar que tengan una experiencia agradable desde el momento en que llegan. Proporcionar asistencia personalizada de atención al cliente durante el evento, ofreciendo información sobre el estadio y atendiendo solicitudes especiales.",
      it: "Accogliere i clienti VIP e garantire che abbiano un'esperienza piacevole dal momento del loro arrivo. Fornire assistenza personalizzata per il servizio clienti durante l'evento, offrendo informazioni sullo stadio e gestendo richieste speciali.",
      de: "VIP-Kunden willkommen heißen und sicherstellen, dass sie vom Moment ihrer Ankunft an eine angenehme Erfahrung haben. Personalisierte Kundenservice-Assistenz während der Veranstaltung, mit Informationen über das Stadion und besonderen Anfragen.",
      fr: "Accueillir les clients VIP et garantir qu'ils ont une expérience agréable dès leur arrivée. Fournir une assistance personnalisée au service client pendant l'événement, offrant des informations sur le stade et traitant les demandes spéciales.",
    },
    achievements: {
      en: [
        "Professional customer service at Santiago Bernabéu stadium",
        "Personalized attention for VIP guests during high-profile events",
        "Team coordination to deliver premium customer experience",
      ],
      es: [
        "Atención profesional al cliente en el estadio Santiago Bernabéu",
        "Atención personalizada para invitados VIP durante eventos de alto nivel",
        "Coordinación de equipo para ofrecer experiencia premium al cliente",
      ],
      it: [
        "Servizio clienti professionale allo stadio Santiago Bernabéu",
        "Attenzione personalizzata per gli ospiti VIP durante eventi di alto profilo",
        "Coordinamento del team per offrire un'esperienza cliente premium",
      ],
      de: [
        "Professioneller Kundenservice im Santiago Bernabéu Stadion",
        "Personalisierte Betreuung für VIP-Gäste bei hochkarätigen Veranstaltungen",
        "Teamkoordination zur Bereitstellung eines Premium-Kundenerlebnisses",
      ],
      fr: [
        "Service client professionnel au stade Santiago Bernabéu",
        "Attention personnalisée pour les invités VIP pendant les événements de haut niveau",
        "Coordination d'équipe pour offrir une expérience client premium",
      ],
    },
    techStack: ["High-End Customer Service", "Team Coordination", "Problem Solving", "Protocol & Events"],
    impactMetrics: {
      en: [
        "500+ VIP guests served per match day with 100% satisfaction",
        "Seamless event protocol implementation with Santiago Bernabéu staff",
      ],
      es: [
        "500+ invitados VIP atendidos por partido con 100% de satisfacción",
        "Implementación fluida de protocolo de eventos con el equipo del Bernabéu",
      ],
      it: [
        "Oltre 500 ospiti VIP serviti per partita con soddisfazione al 100%",
        "Implementazione fluida del protocollo eventi con lo staff del Santiago Bernabéu",
      ],
      de: [
        "500+ VIP-Gäste pro Spieltag mit 100 % Zufriedenheit betreut",
        "Reibungslose Umsetzung von Veranstaltungsprotokollen mit dem Stadionpersonal",
      ],
      fr: [
        "500+ invités VIP accueillis par jour de match avec 100 % de satisfaction",
        "Mise en œuvre fluide du protocole d'événements avec l'équipe du stade",
      ],
    },
    teamSize: {
      en: "Events team",
      es: "Equipo de eventos",
      it: "Team eventi",
      de: "Events-Team",
      fr: "Équipe d'événements",
    },
    image: "/exp/NewLine.webp",
    website: "https://www.newlineevents.es/",
  },
  {
    company: "Coop. soc. IL SOGNO arl",
    role: {
      en: "Web and Network Maintenance Technician",
      es: "Técnico de Mantenimiento Web y Redes",
      it: "Tecnico di Manutenzione Web e Reti",
      de: "Web- und Netzwerkwartungstechniker",
      fr: "Technicien de Maintenance Web et Réseaux",
    },
    period: {
      en: "Mar 2022 - Jun 2022",
      es: "Mar 2022 - Jun 2022",
      it: "Mar 2022 - Giu 2022",
      de: "Mär 2022 - Jun 2022",
      fr: "Mar 2022 - Jun 2022",
    },
    description: {
      en: "Part of a dedicated and dynamic group keeping the network and office equipment in top shape. Maintained one of the company websites, ensuring everything ran smoothly and customers had the best possible experience. Erasmus+ WBL placement in Rome, Italy.",
      es: "Parte de un grupo dedicado y dinámico que mantiene la red y el equipo de oficina en óptimas condiciones. Mantuvo uno de los sitios web de la empresa, asegurando que todo funcionara correctamente y los clientes tuvieran la mejor experiencia posible. Prácticas Erasmus+ WBL en Roma, Italia.",
      it: "Parte di un gruppo dedicato e dinamico che mantiene la rete e le attrezzature per ufficio in ottime condizioni. Ha mantenuto uno dei siti web dell'azienda, garantendo che tutto funzionasse correttamente e che i clienti avessero la migliore esperienza possibile. Tirocinio Erasmus+ WBL a Roma, Italia.",
      de: "Teil einer engagierten und dynamischen Gruppe, die das Netzwerk und die Büroausrüstung in bestem Zustand hält. Wartete eine der Firmenwebsites, stellte sicher, dass alles reibungslos lief und Kunden die bestmögliche Erfahrung hatten. Erasmus+ WBL-Praktikum in Rom, Italien.",
      fr: "Partie d'un groupe dédié et dynamique maintenant le réseau et l'équipement de bureau en parfait état. A maintenu l'un des sites web de l'entreprise, garantissant que tout fonctionnait correctement et que les clients avaient la meilleure expérience possible. Stage Erasmus+ WBL à Rome, Italie.",
    },
    achievements: {
      en: [
        "Network infrastructure and office equipment maintenance",
        "Company website maintenance, security updates, and performance optimization",
        "Erasmus+ international work experience in Rome, Italy",
      ],
      es: [
        "Mantenimiento de infraestructura de redes y equipos de oficina",
        "Mantenimiento del sitio web corporativo, actualizaciones de seguridad y optimización",
        "Experiencia laboral internacional Erasmus+ en Roma, Italia",
      ],
      it: [
        "Manutenzione dell'infrastruttura di rete e delle attrezzature per ufficio",
        "Manutenzione del sito web aziendale, aggiornamenti di sicurezza e ottimizzazione",
        "Esperienza lavorativa internazionale Erasmus+ a Roma, Italia",
      ],
      de: [
        "Wartung der Netzwerkinfrastruktur und Bürogeräte",
        "Wartung der Unternehmenswebsite, Sicherheitsupdates und Leistungsoptimierung",
        "Erasmus+ internationale Berufserfahrung in Rom, Italien",
      ],
      fr: [
        "Maintenance de l'infrastructure réseau et des équipements de bureau",
        "Maintenance du site web de l'entreprise, mises à jour de sécurité et optimisation",
        "Expérience professionnelle internationale Erasmus+ à Rome, Italie",
      ],
    },
    techStack: ["Network Maintenance", "CMS", "HTML/CSS", "Systems Security", "Erasmus+ WBL"],
    impactMetrics: {
      en: [
        "Zero unplanned network downtime during 3-month placement",
        "Successful international technical collaboration in Rome, Italy",
      ],
      es: [
        "Cero tiempo de inactividad de red durante las prácticas de 3 meses",
        "Colaboración técnica internacional exitosa en Roma, Italia",
      ],
      it: [
        "Zero tempi di inattività di rete durante il tirocinio di 3 mesi",
        "Collaborazione tecnica internazionale di successo a Roma, Italia",
      ],
      de: [
        "Null ungeplante Netzwerk-Ausfallzeiten während des 3-monatigen Praktikums",
        "Erfolgreiche internationale technische Zusammenarbeit in Rom, Italien",
      ],
      fr: [
        "Zéro interruption réseau imprévue pendant le stage de 3 mois",
        "Collaboration technique internationale réussie à Rome, Italie",
      ],
    },
    teamSize: {
      en: "Small team (Rome)",
      es: "Equipo pequeño (Roma)",
      it: "Piccolo team (Roma)",
      de: "Kleines Team (Rom)",
      fr: "Petite équipe (Rome)",
    },
    image: "/exp/GentiEPaesi.webp",
    website: "https://gentiepaesi.com/",
  },
];
