import { ProjectProps } from "../types/projects";

export const personalProjects: ProjectProps[] = [
  {
    title: "AWS S3 Bucket Manager",
    image: "/projects/s3man.webp",
    github: "https://github.com/SMG-web-dev/S3BucketManager",
    live: "https://github.com/SMG-web-dev/S3BucketManager",
    technologies: ["HTML", "Spring", "Tailwind", "Docker", "AWS"],
    category: "Full-Stack",
  },
  {
    title: "CryptoTracker (In Progress)",
    image: "/projects/crypto.webp",
    github: "https://github.com/SMG-web-dev/CryptoTracker",
    live: "https://smg-dev-criptos.netlify.app/",
    technologies: ["React", "TypeScript", "Tailwind"],
    category: "Frontend",
  },
  {
    title: "FSC TopNutrition (In Progress)",
    image: "/projects/topnutrition.webp",
    github: null,
    live: "https://fsctopnutrition.es",
    technologies: ["NextJS", "Tailwind"],
    category: "Full-Stack",
  },
  {
    title: "BootLearn",
    image: "/projects/bootLearn.webp",
    github: "https://github.com/SMG-web-dev/BootLearn",
    live: "https://bootlearn.netlify.app/",
    technologies: ["JavaScript", "HTML", "CSS", "Bootstrap"],
    category: "Frontend",
  },
  {
    title: "SuRótulo Website",
    image: "/projects/suRotulo.webp",
    github: "https://github.com/SMG-web-dev/SuRotulo",
    live: "https://surotulo.netlify.app/",
    technologies: ["JavaScript", "HTML", "SASS"],
    category: "Frontend",
  },
];

export const professionalProjects: ProjectProps[] = [
  {
    title: "ITB",
    image: "/projects/DLTCode-horizontal.svg",
    github: null,
    live: "https://www.incibe.es/industria-cpi/dltcode-sl",
    technologies: ["SASS", "NextJS", "TypeScript"],
    category: "Frontend",
    isProfessional: true,
  },
  {
    title: "S@IC",
    image: "/projects/DLTCode-horizontal.svg",
    github: null,
    live: "https://www.incibe.es/industria-cpi/dltcode-sl",
    technologies: ["SASS", "NextJS", "TypeScript"],
    category: "Frontend",
    isProfessional: true,
  },
  {
    title: "ATS",
    image: "/projects/Correcta-horizontal.svg",
    github: null,
    live: "https://www.incibe.es/industria-cpi/correcta-digital-sl",
    technologies: ["SASS", "NextJS", "TypeScript"],
    category: "Frontend",
    isProfessional: true,
  },
  {
    title: "Osborne",
    image: "/projects/Correcta-horizontal.svg",
    github: null,
    live: "https://www.incibe.es/industria-cpi/correcta-digital-sl",
    technologies: ["SASS", "NextJS", "TypeScript"],
    category: "Frontend",
    isProfessional: true,
  },
  {
    title: "DStar",
    image: "/projects/DLTCode-horizontal.svg",
    github: null,
    live: "https://www.incibe.es/industria-cpi/dltcode-sl",
    technologies: ["SASS", "NextJS", "TypeScript"],
    category: "Frontend",
    isProfessional: true,
  },
];
