import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaJava,
  FaNodeJs,
  FaAws,
  FaReact,
  FaPhp,
  FaLinux,
  FaGitAlt,
  FaDocker,
  FaSass,
  SiTypescript,
  SiMysql,
  SiNextdotjs,
  SiTailwindcss,
  SiBootstrap,
  SiSpring,
  SiSupabase,
  SiAnthropic,
  SiNetlify,
  SiVercel,
  SiJsonwebtokens,
  SiGooglegemini,
  SiMeta,
  SiGoogle,
  BiLogoPostgresql,
} from "./icons";

export const techStackCategories = [
  {
    name: "techstack.coreArchitecture",
    techstack: [
      { icon: SiTypescript, name: "TypeScript", color: "from-blue-500 to-blue-700" },
      { icon: FaJs, name: "JavaScript", color: "from-yellow-400 to-yellow-600" },
      { icon: FaReact, name: "React", color: "from-cyan-400 to-cyan-600" },
      { icon: SiNextdotjs, name: "Next.js", color: "from-gray-600 to-gray-800" },
      { icon: FaNodeJs, name: "Node.js", color: "from-green-400 to-green-600" },
      { icon: SiTailwindcss, name: "TailwindCSS", color: "from-teal-400 to-teal-600" },
      { icon: FaJava, name: "Java", color: "from-red-400 to-red-600" },
      { icon: FaHtml5, name: "HTML5", color: "from-orange-400 to-orange-600" },
    ],
  },
  {
    name: "techstack.backendDatabases",
    techstack: [
      { icon: BiLogoPostgresql, name: "PostgreSQL", color: "from-blue-700 to-blue-900" },
      { icon: SiSupabase, name: "Supabase", color: "from-green-400 to-green-600" },
      { icon: SiMysql, name: "MySQL", color: "from-blue-400 to-blue-600" },
      { icon: SiSpring, name: "Spring Boot", color: "from-green-500 to-green-700" },
      { icon: FaPhp, name: "PHP", color: "from-purple-400 to-purple-600" },
    ],
  },
  {
    name: "techstack.cloudDevops",
    techstack: [
      { icon: FaDocker, name: "Docker", color: "from-blue-400 to-blue-600" },
      { icon: FaAws, name: "AWS", color: "from-yellow-500 to-yellow-700" },
      { icon: SiVercel, name: "Vercel", color: "from-gray-700 to-black" },
      { icon: SiNetlify, name: "Netlify", color: "from-teal-400 to-teal-600" },
      { icon: FaGitAlt, name: "Git", color: "from-orange-500 to-orange-700" },
      { icon: FaLinux, name: "Linux", color: "from-yellow-500 to-yellow-700" },
    ],
  },
  {
    name: "techstack.aiEngineering",
    techstack: [
      { icon: SiJsonwebtokens, name: "MCP Protocol", color: "from-indigo-400 to-indigo-600" },
      { icon: SiMeta, name: "Meta AI", color: "from-blue-600 to-blue-800" },
      { icon: SiGoogle, name: "Google Ecosystem", color: "from-red-500 to-yellow-500" },
      { icon: SiAnthropic, name: "Claude API", color: "from-orange-400 to-orange-600" },
      { icon: SiGooglegemini, name: "Gemini API", color: "from-blue-400 to-blue-600" },
    ],
  },
];
